services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            -   "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        shm_size: 128mb

volumes:
        pg_data: