spring:
    application:
        name: learning-spring
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yml
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: validate
    freemarker:
        template-loader-path: classpath:/templates/
        suffix: .ftl
        expose-request-attributes: true
        expose-session-attributes: true
        settings:
            number_format: ""
    mail:
        host: smtp.gmail.com
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        port: 465
        protocol: smtps
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB
upload:
    path: /home/parallels/app/uploads/
app:
    activation-url: http://10.211.55.10/activate/
